#!/usr/bin/env python3
"""
Simple script to extract MediaPipe face mesh connections for hardcoding.
This eliminates the need to import mediapipe in production code.

Usage: python extract_mediapipe_connections.py
"""

try:
    import mediapipe as mp
    
    print("# MediaPipe Face Mesh Connections (FACEMESH_CONTOURS)")
    print("# Generated by extract_mediapipe_connections.py")
    print("# Use this to hardcode connections without importing mediapipe")
    print()
    
    # Get the connections
    connections = list(mp.solutions.face_mesh.FACEMESH_CONTOURS)
    
    print("FACE_CONNECTIONS = [")
    for i, connection in enumerate(connections):
        if i == len(connections) - 1:
            print(f"    {connection}")
        else:
            print(f"    {connection},")
    print("]")
    
    print()
    print(f"# Total connections: {len(connections)}")
    print("# Connection format: (start_landmark_idx, end_landmark_idx)")
    print("# Landmarks are 0-indexed from MediaPipe's 468-point face model")
    
except ImportError:
    print("ERROR: MediaPipe not installed. Install with: pip install mediapipe")
except Exception as e:
    print(f"ERROR: {e}")